### PR TITLE
Fixes #9584: making custom field serializers for EnumMap and LinkedHashMap ready for Java 17

### LINKED ISSUE #9584: Illegal reflective access with Java 9 in LinkedHashMap_CustomFieldSerializer
**GWT version: 2.8.2** 
**Browser (with version): Happens on server side: gwt-servlet.jar** 
**Operating System: Windows 10** 

---

##### Description

Run the following snippet with tomcat 8.5 under java 9 produces this output:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.skife.jdbi.cglib.core.ReflectUtils$1 (file:/C:/dev/workspaces/dmm/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dmmWeb/WEB-INF/lib/jdbi-2.78.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.skife.jdbi.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

##### Steps to reproduce

Run the following snippet with tomcat 8.5 under java 9: 

https://gist.github.com/mseele/8ec870fa240d74a9a80a1754ed4bda9b

### PR DESCRIPTION
**Pull request by axeluhl**
Here is a fix proposal for the `EnumMap` custom field serializer and the `LinkedHashMap` custom field serializer. Both are using reflection to read private fields from `java.*` classes, and while LinkedHashMap can work around this, `EnumMap` has a problem when the map to be serialized is empty.

This PR uses a `java.io.ObjectInputStream` specialization and a subclass of `EnumMap` to gain access to the private fields of the `EnumMap` instance to be serialized which assumes the names of the fields and the `serialVersionUID` of `EnumMap` remain unchanged (which is also what the previous code did when using reflection for a private field).

The full test suite found no issues. https://github.com/axeluhl/gwt/actions/runs/3759098686

Fixes #9584

### CODE REVIEW

File: user/src/com/google/gwt/user/server/rpc/EnumMap.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+    s.defaultReadObject();
+    // Read in size (number of Mappings)
+    int numberOfMappings = s.readInt();
+    // Read the keys and values, and put the mappings in the HashMap
+    for (int i = 0; i < numberOfMappings; i++) {
+      s.readObject(); // key
+      s.readObject(); // value
+    }
+  }
+}
```
Comment (niloc132) [inline user/src/com/google/gwt/user/server/rpc/EnumMap.java:72]: missing trailing newline

Comment (axeluhl) [reply user/src/com/google/gwt/user/server/rpc/EnumMap.java]: See 9d4286e1cc54fbf043649c59b68853488cdb8792

File: user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+ * the first key is obtained from the {@link EnumMap#keySet() key set} and its type is determined
+ * and returned. If the map is empty, it is serialized into an {@link ObjectOutputStream} writing to
+ * a {@link ByteArrayOutputStream} from which it is read again with a specialized
+ * {@link ObjectInputStream}where the {@code resolveClass} method is overridden. Upon reading a
+ * class descriptor for class {@link java.util.EnumMap}, instead of regularly resolving the class
+ * descriptor a package-protected class {@link com.sap.sse.util.EnumMap} is returned which has a
+ * serial version UID equal to that of {@link java.util.EnumMap} and the same set of fields. By
+ * having the same simple name (despite living in a different package) the {@link ObjectInputStream}
+ * considers this class to be compatible to {@link java.util.EnumMap} and de-serializes the stream
+ * contents into an instance of {@link com.sap.sse.util.EnumMap} which in turn offers a public
```
[the remark this answers is not in the document]
Comment (axeluhl) [reply user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java]: See 9d4286e1cc54fbf043649c59b68853488cdb8792

File: user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java [hunk 3]
```diff
@@ -105,15 +108,30 @@ private static boolean getAccessOrder(LinkedHashMap instance) {
     if (!reflectionHasFailed.get()) {
       try {
         Field f = accessOrderField.get();
-        if (f == null || !f.isAccessible()) {
+        boolean isAccessible = f != null && f.isAccessible();
```
[the remark this answers is not in the document]
Comment (axeluhl) [reply user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java:111]: Under which condition do you think can this happen? If the field cannot be made accessible, the old fall-back to getAccessOrderNoReflection is still in place, correct but slow.

[the remark this answers is not in the document]
Comment (niloc132) [reply user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java:111]: Thank you, I've confirmed that I misunderstood the scope of this change.

File: user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java [hunk 4]
```diff
@@ -105,15 +108,30 @@ private static boolean getAccessOrder(LinkedHashMap instance) {
...
+              // Ensure all threads can see the accessibility.
+              f.setAccessible(true);
+              accessOrderField.set(f);
+              isAccessible = true;
+            }
           }
-          accessOrderField.set(f);
         }
-        return ((Boolean) f.get(instance)).booleanValue();
+        if (isAccessible) {
```
Comment (niloc132) [inline user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java:132]: To confirm (but not necessarily objecting to this change), this `if` isn't strictly required, since `Field.get()` will throw an IllegalAccessException, which will fall through and still land on the `reflectionHasFailed.set(true)` below, right?

If so, we only need the trySetAccessible/setAccessible change above, and the additional catch block

File: user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java [hunk 5]
```diff
@@ -105,15 +108,30 @@ private static boolean getAccessOrder(LinkedHashMap instance) {
...
-        if (f == null || !f.isAccessible()) {
+        boolean isAccessible = f != null && f.isAccessible();
+        if (!isAccessible) {
           f = LinkedHashMap.class.getDeclaredField("accessOrder");
           synchronized (f) {
-            // Ensure all threads can see the accessibility.
-            f.setAccessible(true);
+            try {
+              // see if we can *try* setting the accessOrder field accessible:
+              final Method trySetAccessible = AccessibleObject.class.getDeclaredMethod("trySetAccessible");
```
Comment (niloc132) [inline user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java:117]: Please wrap this line, as it adds a new checkstyle warning (see the diff tab for where it is logged in this review

File: user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+ * </pre>
+ * <p>
+ * 
+ * Implementation note: If the map passed to {@link #getKeyType(java.util.EnumMap)} is not empty,
+ * the first key is obtained from the {@link EnumMap#keySet() key set} and its type is determined
+ * and returned. If the map is empty, it is serialized into an {@link ObjectOutputStream} writing to
+ * a {@link ByteArrayOutputStream} from which it is read again with a specialized
+ * {@link ObjectInputStream}where the {@code resolveClass} method is overridden. Upon reading a
+ * class descriptor for class {@link java.util.EnumMap}, instead of regularly resolving the class
+ * descriptor a package-protected class {@link com.google.gwt.user.server.rpc.EnumMap} is returned which has a
```
Comment (niloc132) [inline user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java:47]: Please check the diff and wrap the long lines in this file

File: user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java (hunk 4 above)
Comment (axeluhl) [reply user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java:132]: The "if" is supposedly faster than letting the code run into an exception that needs to be caught. That's why I added it.

File: user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java (hunk 5 above)
Comment (axeluhl) [reply user/src/com/google/gwt/user/client/rpc/core/java/util/LinkedHashMap_CustomFieldSerializer.java]: Thanks for pointing this out. The GWT formatter correctly breaks this line. cad8ec716495d3740fd7dbfea9fbbeef9e644c7d

File: user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java (hunk 6 above)
Comment (axeluhl) [reply user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java]: Same as above. Fixed with a838a02fbfa96c2b806e57005d3667bb7763ca4d.

File: user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java [hunk 7]
```diff
@@ -0,0 +1,99 @@
...
+    protected Class<?> resolveClass(ObjectStreamClass desc) throws IOException,
+        ClassNotFoundException {
+      Class<?> result = null;
+      if (desc.getName().equals("java.util.EnumMap")) {
+        result = EnumMap.class;
+      } else {
+        try {
+          result = super.resolveClass(desc);
+        } catch (ClassNotFoundException e) {
+          result = Class.forName(desc.getName(), false, Thread.currentThread().getContextClassLoader());
```
Comment (niloc132) [inline user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java:73]: diff still reports this line as being too long

Comment (axeluhl) [reply user/src/com/google/gwt/user/server/rpc/EnumMapUtil.java]: a2b7b5c7770643faec4115a07d1d36b2c0da133c. Sorry, should be ok now.

**Review by niloc132 — APPROVED** [review]

**Comment by atavanamir** [comment]
@axeluhl  thanks for this fix! We experience the same problem after switching to J17.

Is this ready to merge?  Is there any guess when it will be released? @niloc132
